### ISSUE TITLE
Managing NUS packages

### ISSUE THREAD

**Issue by TheManuel2** [Exzap/ZArchive#1]
Hi.
Would it make sense to expand the scope of this tool to be able to decrypt and convert encrypted NUS packages directly to NUS, with the ability to restore them back to their original state?
That would be useful from a preservation and efficiency standpoint, as one set of files for each game would serve all purposes.

**Comment by Exzap** [comment]
If anyone wants to build a lossless NUS converter on top of this they are free to do so but there is almost zero overlap with existing code (it's really just a generic archive format, as generic as something like .zip), so imho it should be its own separate project.

**Comment by TheManuel2** [comment]
Understood.  Thanks.
