### ISSUE TITLE
[Request] Support WUD & WUX files

### ISSUE THREAD

**Issue by SamRohod** [Exzap/ZArchive#13]
ZArchive currently supports the fallowing conversions:

**Extracted Folder ----> .zar (wua)**
**.zar (wua) ----> Extracted Folder**

is it possible to add support for:

**.wud/wux ----> .zar/.wua**
**.zar/.wua ----> .wud/wux**

& (if even possible)

**Extracted Folder ----> .wud/wux**
**.wud/wux ----> Extracted Folder**

This way we can store all the Wii U disc dumps as .zar/.wua and be able to convert them back to their original dumping format (for hash verification) without the need for Cemu. Making the ZArchive format (.zar/.wua) truly archival (everything can be turned back to the way it was originally dumped).

**I'm just an idiot. The rest of this is just me basically guessing without actual expertise**
--------

If I understand correctly, this might need the user to input a key for   .wud/wux --> .zar/.wua   but if the key can also be stored in the .zar/.wua file, then   .zar/.wua --> .wud/wux   can be possible without a key.

I don't know if there are random seeds for the .wud file padding or not, but tools like WudCompress can convert between .wud and .wux with archival quality (hash doesn't change for the .wud file). So, I assume the padding has a pattern to it.

This might also need some understanding of the files layout of the original .wud/.wux file. Something like IRD files for PS3 discs (layout information). If this layout information can stored in the .zar/.wua file during conversion and also be exported to a file (like IRD files for the PS3), then maybe these conversions could be possible:

**.wud/wux + key file/text + Layout file ----> .zar/.wua**
**.zar/.wua ----> .wud/wux + key file/text + Layout file**

**Extracted Folder + key file/text + Layout file ----> .zar/.wua (convertible to .wud/.wux)**
**.zar/.wua (convertible to .wud/.wux) ----> Extracted Folder + key file/text + Layout file**

**Comment by Exzap** [comment]
The WUA specific logic sits in Cemu so this is kind of the wrong place to ask. Think of ZArchive as a generic file container archive, like `.zip`. WUA just builds on top of ZArchive.

Anyway, while I agree that it would be nice if we could losslessly convert between WUD/WUX and WUA it takes a lot of work to implement this and I personally just don't have the motivation or time to do it. You can open this as a PR feature request in the Cemu repository and *maybe* someone else is willing to look into this.
